name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16' # or the specific version your project requires
      - run: npm cache clean --force
      - run: rm -rf node_modules
      - run: npm install --legacy-peer-deps
      - run: npm run build:app
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BNN_GENZ_MILLENNIALS }}
          channelId: live
          projectId: bnn-genz-millennials
